version: '3'
services:
  web:
    image: "node:8.4.0-alpine"
    build: .
    working_dir: /home/node/app
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
    depends_on:
      - "mongo"
  mongo:
    image: "mongo"

    ports:
      - "27017:27017"
  adminmongo:
    image: "mrvautin/adminmongo"
    ports:
      - "1234:1234"
  